name: Userge Hooman

on:
  push:
    branches: [ hooman ]
    paths-ignore: 'README.md'
  workflow_dispatch:
    
env:
  GitHubMail: "iam.pro2@outlook.com"
  GitHubName: "ProgrammingError"
  PIP_NO_CACHE_DIR: 1
  LANG: "C.UTF-8"
  GOOGLE_CHROME_DRIVER: "/usr/bin/chromedriver"
  GOOGLE_CHROME_BIN: "/usr/bin/google-chrome-stable"
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Setup
         run: |
           git config --global user.email ${GitHubMail}
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           sudo git clone -b alpha https://github.com/iam-pro/USERGE-X.git /app/
           cd /app/
           sudo sed -i.bak 's/us-west-2\.ec2\.//' /etc/apt/sources.list
           sudo apt -qq update && apt -qq upgrade -y && \
           sudo apt -qq install -y --no-install-recommends \
           apt-utils \
           gnupg2 \
           wget \
           unzip \
           procps \
           tree
           sudo mkdir -p /tmp/ && \
           sudo cd /tmp/ && \
           sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
           sudo dpkg -i ./google-chrome-stable_current_amd64.deb; apt -fqqy install && \
           sudo rm ./google-chrome-stable_current_amd64.deb
           sudo mkdir -p /tmp/ && \
           sudo cd /tmp/ && \
           sudo wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip && \
           sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/bin/ && \
           sudo rm /tmp/chromedriver.zip
           sudo apt -qq update && apt -qq install -y --no-install-recommends \
           gcc python3-dev zlib1g-dev \
           apt-transport-https \
           build-essential coreutils jq pv \
           ffmpeg mediainfo \
           neofetch \
           p7zip-full \
           libfreetype6-dev libjpeg-dev libpng-dev libgif-dev libwebp-dev && \
           sudo rm -rf /var/lib/apt/lists /var/cache/apt/archives /tmp/*
           pip install -U setuptools wheel && \
           pip install --no-cache-dir -r requirements.txt
       - name: cloning repo
         continue-on-error: false
         run: |
           git clone -b hooman https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.CREDS }} usergecreds
       - name: Running Userge
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cp usergecreds/ /app/
           rm -rf usergecreds
           bash ./run
       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone -b hooman https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:hooman
